### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by vermut** [Wedjaa/JavaAnsibleVault#1]
Hey, I'm working on Ansible support for IntelliJ IDEA and wanted to [incorporate vault support](https://github.com/vermut/intellij-ansible/issues/33). What is your licence for this code? Can I steal it and sell it for drugs?

**Comment by Wedjaa** [comment]
Hi Pavel!

 Absolutely! Take it and do with it what you want - a mention of my name
would suffice -- but just to be sure, let me add a license and push it
again on github, so that if I go crazy and want part of the drugs you can
say: 'suck it!'

  Fabio

2016-03-24 6:17 GMT-05:00 Pavel Veretennikov notifications@github.com:

**Comment by Wedjaa** [comment]
Released 1.2.0 and 1.2.0-SNAPSHOT under the Apache 2.0 license.
